"""Domain enumerations — shared value types used across the domain."""

from enum import StrEnum, auto


class TradingMode(StrEnum):
    """Operating mode for the trading engine."""

    LOCAL = "local"  # No broker connection — simulated data
    PAPER = "paper"  # OANDA practice trading account
    LIVE = "live"  # Real trading with real capital


class OrderSide(StrEnum):
    """Direction of a trade order."""

    BUY = "buy"
    SELL = "sell"


class SignalType(StrEnum):
    """Type of signal generated by a strategy."""

    LONG = auto()  # Enter or hold a long position
    SHORT = auto()  # Enter or hold a short position
    FLAT = auto()  # No position / exit all


class OrderType(StrEnum):
    """Type of order execution."""

    MARKET = "market"  # Execute immediately at current market price
    LIMIT = "limit"  # Execute only at specified price or better


class OrderStatus(StrEnum):
    """Lifecycle status of an order."""

    PENDING = "pending"
    SUBMITTED = "submitted"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


class RiskAction(StrEnum):
    """Risk engine decision outcome."""

    APPROVED = "approved"
    REJECTED = "rejected"
    KILL_SWITCH = "kill_switch"
