"""Domain models — immutable data structures representing core trading concepts.

All models are frozen dataclasses with no external dependencies.
They form the shared language between strategy, risk, execution, and persistence.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from uuid import UUID, uuid4

from aurex_trade.domain.enums import OrderSide, OrderStatus, OrderType, RiskAction, SignalType


def _utc_now() -> datetime:
    return datetime.now(UTC)


def _new_id() -> UUID:
    return uuid4()


@dataclass(frozen=True)
class BarData:
    """A single OHLCV price bar."""

    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    symbol: str


@dataclass(frozen=True)
class Signal:
    """A trading signal generated by a strategy."""

    id: UUID = field(default_factory=_new_id)
    timestamp: datetime = field(default_factory=_utc_now)
    symbol: str = ""
    signal_type: SignalType = SignalType.FLAT
    strategy_name: str = ""
    strength: float = 0.0
    metadata: dict[str, str] = field(default_factory=dict)
    stop_loss: float | None = None
    take_profit: float | None = None


@dataclass(frozen=True)
class RiskDecision:
    """The risk engine's verdict on a signal."""

    signal_id: UUID = field(default_factory=_new_id)
    action: RiskAction = RiskAction.REJECTED
    reason: str = ""
    timestamp: datetime = field(default_factory=_utc_now)


@dataclass(frozen=True)
class Order:
    """A trade order to be placed with a broker.

    MVP uses MARKET orders (immediate fill at current price). LIMIT orders are
    supported in the model for future use — they require a limit_price and
    additional management logic (unfilled order handling, timeouts, price
    adjustments) that is not yet implemented.
    """

    id: UUID = field(default_factory=_new_id)
    signal_id: UUID = field(default_factory=_new_id)
    symbol: str = ""
    side: OrderSide = OrderSide.BUY
    order_type: OrderType = OrderType.MARKET
    quantity: float = 0.0
    limit_price: float | None = None  # Required for LIMIT orders, None for MARKET
    stop_loss: float | None = None  # Stop-loss price level (for broker to respect)
    take_profit: float | None = None  # Take-profit price level (for broker to respect)
    status: OrderStatus = OrderStatus.PENDING
    timestamp: datetime = field(default_factory=_utc_now)


@dataclass(frozen=True)
class Trade:
    """A completed (filled) trade.

    One Trade per Order. The price is the average fill price reported by the
    broker. If the broker fills in multiple chunks (e.g. 6 @ $180.00 +
    4 @ $180.05), price is the weighted average ($180.02).

    Future consideration: for detailed fill tracking, introduce a separate Fill
    model with one record per partial fill, linked to the Trade via trade_id.
    """

    id: UUID = field(default_factory=_new_id)
    order_id: UUID = field(default_factory=_new_id)
    symbol: str = ""
    side: OrderSide = OrderSide.BUY
    quantity: float = 0.0
    price: float = 0.0
    commission: float = 0.0
    timestamp: datetime = field(default_factory=_utc_now)


@dataclass(frozen=True)
class Position:
    """Current position in a symbol."""

    symbol: str = ""
    quantity: float = 0.0
    average_cost: float = 0.0
    market_value: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    timestamp: datetime = field(default_factory=_utc_now)


@dataclass(frozen=True)
class AccountState:
    """Snapshot of account state for risk evaluation.

    Passed to RiskEngine.evaluate() so it can enforce drawdown limits
    and calculate position sizes without depending on broker adapters.
    """

    equity: float = 0.0
    peak_equity: float = 0.0


@dataclass(frozen=True)
class User:
    """Authenticated user identity."""

    id: str
    email: str
    name: str
    avatar_url: str = ""


@dataclass(frozen=True)
class OAuthUserInfo:
    """User info returned by an OAuth provider."""

    sub: str
    email: str
    name: str
    picture: str = ""


@dataclass(frozen=True)
class SessionData:
    """An active user session."""

    session_id: str
    user_id: str
    created_at: datetime
    expires_at: datetime
